### ISSUE TITLE
Add a version check like Morph's Rtver.dll

### ISSUE THREAD

**Issue by LadyAlekto** [IceRaptor/IRTweaks#7]
I copy pasta the talk pieces from discord here since brain bad at words

---

@FrostRaptor got a question, can you include @Morphyum  version info dll function into ir tweaks?

i could shuffle the dll and its pieces straight into the core folder that way

FrostRaptorToday at 18:39
@Precentor Rho not sure what you're asking LA. What is the 'Version info DLL'?
You mean the one that displays 'RT version X.Y' on the logo screen?
 
Precentor RhoToday at 18:39
yes

---

**Comment by IceRaptor** [comment]
Already implemented by Jamie in another place.
